### ISSUE TITLE
Feature: Multiple streams/channels

### ISSUE THREAD

**Issue by cmaddick** [GRVYDEV/Project-Lightspeed#9]
Title is really self descriptive. Would be really cool to have the ability to make multiple feeds available.

Fantastic work so far @GRVYDEV, I've been looking for something like this for a while!

**Comment by GRVYDEV** [comment]
While this would be cool I am not exactly sure that this is where I want this project to go. I will keep it in mind though! Best case scenario this wont be added for a while anyways

**Comment by krakow10** [comment]
Does this mean multiple video and audio tracks for a single streamer, or is it meant as a suggestion to allow more than one streamer to use the same server with different streams?  As for the former, I imagine a livestream with two video tracks where the viewer can change the location and size of the face camera or disable it entirely, and independently change the volume of two or more audio tracks such as game audio, voice, and music.

**Comment by GRVYDEV** [comment]
> Does this mean multiple video and audio tracks for a single streamer, or is it meant as a suggestion to allow more than one streamer to use the same server with different streams? As for the former, I imagine a livestream with two video tracks where the viewer can change the location and size of the face camera or disable it entirely, and independently change the volume of two or more audio tracks such as game audio, voice, and music.

This would be awesome... but a nightmare as it would involve making OBS send multiple streams to the server and that would take a lot of modification to OBS

**Comment by woodrowbarlow** [comment]
I would like to +1 this feature request and volunteer some time to work on this. Early 2020 I went about setting up my own streaming server and found the landscape to be pretty empty. Your project goes end-to-end, even including a frontend, and is more straightforward and self-contained than anything else out there. This project has a lot of potential, great job!

I've been thinking about what it would take to turn the backend (ingest + webrtc) into a multi-tenant server (can receive multiple streams from multiple origins and send each to a unique webrtc endpoint). It would definitely involve collaboration between ingest and webrtc, in the form of sharing config and communicating events to each other.

In other words, I'm imagining a server that could be configured something like this, where you explicitly define each endpoint:

```toml
[server]
# the websocket port
webrtc-port = 8080
# need to have a "pool" of RTP ports that can be handed out in FTL handshakes
# the backend isn't listening to any of these at first, but when a handshake is finalizing,
# the backend chooses one available port from this pool, marks it in-use, and starts
# listening on that port. when a stream disconnects, need to put its port back into
# the pool.
rtp-port-range-start = 65535
rtp-port-range-end = 65555

[streams]

[streams.default]
# "default" is just the stream name used for logging
# path is used to build the websocket URL. so to view this stream, the frontend will
# open a websocket to http(s)://example.com:8080/websocket
path = "websocket"
# this is the channel id used to derive the stream key. the "server" config section would
# probably need a "hmac" config value, pair those together to generate the stream key.
channel = 123456789

[streams.example]
path = "test"
channel = 987654321
```

With all the communication between "ingest" and "webrtc" (to open/close UDP for RTP ports, and to start/stop accepting requests at certain websocket URLs, all in response to handshakes), it would be a lot easier if the backend were a single binary. I see that Rust's webrtc implementation is not ready for use, which explains why Go handles those parts. But given the simplicity of the FTL handshaking process, it is conceivable that the Go code could do the handshake as well as its current roles.

Would you consider a PR that subsumes the ingest project *into* the webrtc project, creating a single Go binary for the entire backend? This would be a preliminary step towards multi-tenent, the next step would probably be to add a configuration system.
